services:
  app:
    build: .
    environment:
      - DB_HOST=db  # <-- Gunakan nama service
      - DB_PORT=5432

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"  # Port di host (untuk akses dari luar Docker)
